#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-CI

on:
  push:
    branches: 
      - master
    schedule:
      - cron: 0 20 * * *
  release:
    types: [published]

jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir
          # ln -s -f /mnt/openwrt/build_dir/host ./build_dir/host
          # ln -s -f /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir

          df -h

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config

          #
          # 在 cat >> .config <<EOF 到 EOF 之间粘贴你的编译配置, 需注意缩进关系
          # 例如:
		
		cat >> .config <<EOF
		CONFIG_TARGET_x86=y
		CONFIG_TARGET_x86_64=y
		CONFIG_TARGET_x86_64_DEVICE_generic=y
		CONFIG_COREMARK_NUMBER_OF_THREADS=32
		CONFIG_DOCKER_CGROUP_OPTIONS=y
		CONFIG_DOCKER_NET_MACVLAN=y
		CONFIG_DOCKER_STO_EXT4=y
		CONFIG_GRUB_IMAGES=y
		CONFIG_KERNEL_CGROUP_DEVICE=y
		CONFIG_KERNEL_CGROUP_FREEZER=y
		CONFIG_KERNEL_CGROUP_NET_PRIO=y
		CONFIG_KERNEL_EXT4_FS_POSIX_ACL=y
		CONFIG_KERNEL_EXT4_FS_SECURITY=y
		CONFIG_KERNEL_FS_POSIX_ACL=y
		CONFIG_KERNEL_NET_CLS_CGROUP=y
		CONFIG_NFS_KERNEL_SERVER_V4=y
		CONFIG_PACKAGE_6in4=y
		CONFIG_PACKAGE_SAMBA_MAX_DEBUG_LEVEL=-1
		CONFIG_PACKAGE_TAR_BZIP2=y
		CONFIG_PACKAGE_TAR_GZIP=y
		CONFIG_PACKAGE_TAR_XZ=y
		CONFIG_PACKAGE_TAR_ZSTD=y
		# CONFIG_PACKAGE_UnblockNeteaseMusic-Go is not set
		# CONFIG_PACKAGE_adbyby is not set
		CONFIG_PACKAGE_adguardhome=y
		# CONFIG_PACKAGE_amdgpu-firmware is not set
		CONFIG_PACKAGE_attr=m
		CONFIG_PACKAGE_avahi-dbus-daemon=m
		CONFIG_PACKAGE_bash=y
		CONFIG_PACKAGE_boost=y
		CONFIG_PACKAGE_boost-program_options=y
		CONFIG_PACKAGE_boost-system=y
		CONFIG_PACKAGE_brook=y
		CONFIG_PACKAGE_btrfs-progs=y
		CONFIG_PACKAGE_bzip2=y
		CONFIG_PACKAGE_cgroupfs-mount=y
		CONFIG_PACKAGE_chinadns-ng=y
		CONFIG_PACKAGE_containerd=y
		CONFIG_PACKAGE_coreutils-nohup=y
		CONFIG_PACKAGE_coreutils-stat=y
		CONFIG_PACKAGE_coreutils-stty=y
		CONFIG_PACKAGE_dbus=m
		CONFIG_PACKAGE_docker=y
		CONFIG_PACKAGE_dockerd=y
		CONFIG_PACKAGE_fdisk=y
		CONFIG_PACKAGE_frpc=y
		CONFIG_PACKAGE_glib2=y
		CONFIG_PACKAGE_haproxy=y
		CONFIG_PACKAGE_hysteria=y
		CONFIG_PACKAGE_ip6tables=y
		CONFIG_PACKAGE_ip6tables-mod-nat=y
		# CONFIG_PACKAGE_iperf3 is not set
		CONFIG_PACKAGE_ipt2socks=y
		CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
		CONFIG_PACKAGE_iptables-mod-iprange=y
		CONFIG_PACKAGE_iptables-mod-socket=y
		CONFIG_PACKAGE_ipv6helper=y
		CONFIG_PACKAGE_kmod-asn1-encoder=y
		CONFIG_PACKAGE_kmod-br-netfilter=y
		CONFIG_PACKAGE_kmod-crypto-ccm=y
		CONFIG_PACKAGE_kmod-crypto-cmac=y
		CONFIG_PACKAGE_kmod-crypto-ctr=y
		CONFIG_PACKAGE_kmod-crypto-cts=y
		CONFIG_PACKAGE_kmod-crypto-rng=y
		CONFIG_PACKAGE_kmod-crypto-seqiv=y
		CONFIG_PACKAGE_kmod-crypto-sha256=y
		CONFIG_PACKAGE_kmod-crypto-sha512=y
		CONFIG_PACKAGE_kmod-dax=y
		CONFIG_PACKAGE_kmod-dm=y
		CONFIG_PACKAGE_kmod-dnsresolver=y
		# CONFIG_PACKAGE_kmod-drm-amdgpu is not set
		CONFIG_PACKAGE_kmod-dummy=y
		CONFIG_PACKAGE_kmod-fs-btrfs=y
		CONFIG_PACKAGE_kmod-fs-cifs=y
		CONFIG_PACKAGE_kmod-fs-exportfs=y
		CONFIG_PACKAGE_kmod-fs-nfs=y
		CONFIG_PACKAGE_kmod-fs-nfs-common=y
		CONFIG_PACKAGE_kmod-fs-nfs-common-rpcsec=y
		CONFIG_PACKAGE_kmod-fs-nfs-ssc=y
		CONFIG_PACKAGE_kmod-fs-nfs-v4=y
		CONFIG_PACKAGE_kmod-fs-nfsd=y
		CONFIG_PACKAGE_kmod-fuse=y
		CONFIG_PACKAGE_kmod-ikconfig=y
		CONFIG_PACKAGE_kmod-ip6tables=y
		CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
		CONFIG_PACKAGE_kmod-ipt-iprange=y
		CONFIG_PACKAGE_kmod-ipt-nat6=y
		CONFIG_PACKAGE_kmod-ipt-socket=y
		CONFIG_PACKAGE_kmod-iptunnel=y
		CONFIG_PACKAGE_kmod-keys-encrypted=y
		CONFIG_PACKAGE_kmod-keys-trusted=y
		CONFIG_PACKAGE_kmod-lib-raid6=y
		CONFIG_PACKAGE_kmod-lib-xor=y
		CONFIG_PACKAGE_kmod-lib-zstd=y
		CONFIG_PACKAGE_kmod-nf-ipt6=y
		CONFIG_PACKAGE_kmod-nf-ipvs=y
		CONFIG_PACKAGE_kmod-nf-log6=y
		CONFIG_PACKAGE_kmod-nf-nat6=y
		CONFIG_PACKAGE_kmod-nf-reject6=y
		CONFIG_PACKAGE_kmod-nf-socket=y
		CONFIG_PACKAGE_kmod-oid-registry=y
		CONFIG_PACKAGE_kmod-random-core=y
		# CONFIG_PACKAGE_kmod-shortcut-fe is not set
		# CONFIG_PACKAGE_kmod-shortcut-fe-cm is not set
		CONFIG_PACKAGE_kmod-sit=y
		# CONFIG_PACKAGE_kmod-tcp-bbr is not set
		CONFIG_PACKAGE_kmod-tpm=y
		# CONFIG_PACKAGE_kmod-usb-net-aqc111 is not set
		CONFIG_PACKAGE_kmod-veth=y
		CONFIG_PACKAGE_libaio=y
		CONFIG_PACKAGE_libavahi-client=m
		CONFIG_PACKAGE_libavahi-dbus-support=m
		CONFIG_PACKAGE_libbz2=y
		CONFIG_PACKAGE_libdaemon=m
		CONFIG_PACKAGE_libdbus=m
		CONFIG_PACKAGE_libdevmapper=y
		CONFIG_PACKAGE_libexpat=m
		CONFIG_PACKAGE_libffi=y
		CONFIG_PACKAGE_libfuse=y
		CONFIG_PACKAGE_libgd=y
		CONFIG_PACKAGE_libgnutls=m
		# CONFIG_PACKAGE_libiperf3 is not set
		CONFIG_PACKAGE_libjpeg-turbo=y
		CONFIG_PACKAGE_libkeyutils=y
		CONFIG_PACKAGE_libltdl=y
		CONFIG_PACKAGE_liblua5.3=y
		CONFIG_PACKAGE_liblzma=y
		CONFIG_PACKAGE_liblzo=y
		CONFIG_PACKAGE_libnettle=m
		CONFIG_PACKAGE_libnetwork=y
		CONFIG_PACKAGE_libpng=y
		CONFIG_PACKAGE_libseccomp=y
		CONFIG_PACKAGE_libtasn1=m
		CONFIG_PACKAGE_liburing=m
		CONFIG_PACKAGE_libwebp=y
		CONFIG_PACKAGE_libwrap=y
		CONFIG_PACKAGE_libzstd=y
		CONFIG_PACKAGE_lsblk=y
		# CONFIG_PACKAGE_lua-neturl is not set
		# CONFIG_PACKAGE_luci-app-accesscontrol is not set
		# CONFIG_PACKAGE_luci-app-adbyby-plus is not set
		CONFIG_PACKAGE_luci-app-adguardhome=y
		CONFIG_PACKAGE_luci-app-advanced-reboot=y
		# CONFIG_PACKAGE_luci-app-bypass_INCLUDE_ShadowsocksR_Libev_Client is not set
		# CONFIG_PACKAGE_luci-app-bypass_INCLUDE_ShadowsocksR_Libev_Server is not set
		# CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Shadowsocks_Libev_Client is not set
		# CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Shadowsocks_Libev_Server is not set
		# CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Simple_Obfs is not set
		# CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Socks_Server is not set
		# CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Trojan is not set
		# CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Xray is not set
		CONFIG_PACKAGE_luci-app-cifs-mount=y
		# CONFIG_PACKAGE_luci-app-ddns is not set
		CONFIG_PACKAGE_luci-app-diskman_INCLUDE_btrfs_progs=y
		CONFIG_PACKAGE_luci-app-diskman_INCLUDE_lsblk=y
		CONFIG_PACKAGE_luci-app-docker=y
		# CONFIG_PACKAGE_luci-app-ipsec-vpnd is not set
		CONFIG_PACKAGE_luci-app-nfs=y
		# CONFIG_PACKAGE_luci-app-nlbwmon is not set
		CONFIG_PACKAGE_luci-app-ntpc=y
		CONFIG_PACKAGE_luci-app-passwall=y
		CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Brook=y
		CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ChinaDNS_NG=y
		CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Hysteria=y
		CONFIG_PACKAGE_luci-app-passwall_INCLUDE_NaiveProxy=y
		CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Server=y
		CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_GO=y
		CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Xray_Plugin=y
		CONFIG_PACKAGE_luci-app-passwall_Iptables_Transparent_Proxy=y
		CONFIG_PACKAGE_luci-app-ramfree=y
		# CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-ng is not set
		# CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-webui is not set
		# CONFIG_PACKAGE_luci-app-ssr-plus is not set
		# CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Libev_Client is not set
		# CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Libev_Server is not set
		CONFIG_PACKAGE_luci-app-store=y
		# CONFIG_PACKAGE_luci-app-turboacc is not set
		# CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_BBR_CCA is not set
		# CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_PDNSD is not set
		# CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_SHORTCUT_FE_CM is not set
		CONFIG_PACKAGE_luci-app-uhttpd=y
		# CONFIG_PACKAGE_luci-app-unblockmusic is not set
		# CONFIG_PACKAGE_luci-app-unblockmusic_INCLUDE_UnblockNeteaseMusic_Go is not set
		CONFIG_PACKAGE_luci-app-vnstat=y
		# CONFIG_PACKAGE_luci-app-vsftpd is not set
		# CONFIG_PACKAGE_luci-app-vssr_INCLUDE_Hysteria is not set
		# CONFIG_PACKAGE_luci-app-vssr_INCLUDE_ShadowsocksR_Libev_Server is not set
		# CONFIG_PACKAGE_luci-app-vssr_INCLUDE_Trojan is not set
		# CONFIG_PACKAGE_luci-app-vssr_INCLUDE_Xray is not set
		# CONFIG_PACKAGE_luci-app-vssr_INCLUDE_Xray_plugin is not set
		# CONFIG_PACKAGE_luci-app-wireguard is not set
		# CONFIG_PACKAGE_luci-app-xlnetacc is not set
		# CONFIG_PACKAGE_luci-app-zerotier is not set
		CONFIG_PACKAGE_luci-compat=y
		CONFIG_PACKAGE_luci-i18n-adguardhome-zh-cn=y
		CONFIG_PACKAGE_luci-i18n-advanced-reboot-zh-cn=y
		CONFIG_PACKAGE_luci-i18n-cifs-mount-zh-cn=y
		CONFIG_PACKAGE_luci-i18n-docker-zh-cn=y
		CONFIG_PACKAGE_luci-i18n-nfs-zh-cn=y
		CONFIG_PACKAGE_luci-i18n-ntpc-zh-cn=y
		CONFIG_PACKAGE_luci-i18n-passwall-zh-cn=y
		CONFIG_PACKAGE_luci-i18n-ramfree-zh-cn=y
		CONFIG_PACKAGE_luci-i18n-uhttpd-zh-cn=y
		CONFIG_PACKAGE_luci-i18n-vnstat-zh-cn=y
		# CONFIG_PACKAGE_luci-lib-ipkg is not set
		CONFIG_PACKAGE_luci-lib-taskd=y
		CONFIG_PACKAGE_luci-lib-xterm=y
		CONFIG_PACKAGE_luci-proto-ipv6=y
		CONFIG_PACKAGE_luci-theme-argonne=y
		CONFIG_PACKAGE_mount-utils=y
		CONFIG_PACKAGE_naiveproxy=y
		CONFIG_PACKAGE_nano=y
		CONFIG_PACKAGE_netdata=y
		CONFIG_PACKAGE_nfs-kernel-server=y
		CONFIG_PACKAGE_nfs-kernel-server-utils=y
		CONFIG_PACKAGE_nfs-utils=y
		CONFIG_PACKAGE_nfs-utils-libs=y
		CONFIG_PACKAGE_ntpclient=y
		CONFIG_PACKAGE_odhcp6c=y
		CONFIG_PACKAGE_odhcp6c_ext_cer_id=0
		CONFIG_PACKAGE_odhcpd-ipv6only=y
		CONFIG_PACKAGE_odhcpd_ipv6only_ext_cer_id=0
		CONFIG_PACKAGE_open-vm-tools=y
		CONFIG_PACKAGE_open-vm-tools-fuse=y
		# CONFIG_PACKAGE_pdnsd-alt is not set
		CONFIG_PACKAGE_rpcbind=y
		CONFIG_PACKAGE_runc=y
		CONFIG_PACKAGE_samba36-server=y
		CONFIG_PACKAGE_samba4-libs=m
		CONFIG_PACKAGE_script-utils=y
		# CONFIG_PACKAGE_shadowsocksr-libev-ssr-check is not set
		CONFIG_PACKAGE_tar=y
		CONFIG_PACKAGE_taskd=y
		CONFIG_PACKAGE_tini=y
		CONFIG_PACKAGE_trojan-go=y
		CONFIG_PACKAGE_trojan-plus=y
		CONFIG_PACKAGE_unzip=y
		CONFIG_PACKAGE_v2ray-core=y
		CONFIG_PACKAGE_v2ray-plugin=y
		CONFIG_PACKAGE_vnstat=y
		CONFIG_PACKAGE_vnstati=y
		CONFIG_PACKAGE_xray-plugin=y
		CONFIG_PACKAGE_xz=y
		CONFIG_PACKAGE_xz-utils=y
		CONFIG_RPCBIND_LIBWRAP=y
		CONFIG_RPCBIND_RMTCALLS=y
		CONFIG_TARGET_KERNEL_PARTSIZE=64
		CONFIG_TARGET_ROOTFS_PARTSIZE=256
		CONFIG_ZSTD_OPTIMIZE_O3=y
		CONFIG_boost-compile-visibility-hidden=y
		CONFIG_boost-runtime-shared=y
		CONFIG_boost-static-and-shared-libs=y
		CONFIG_boost-variant-release=y
		# CONFIG_BUSYBOX_CONFIG_FEATURE_IP_LINK is not set
		# CONFIG_BUSYBOX_CONFIG_IP is not set
		CONFIG_PACKAGE_iptables-mod-ipsec=y
		CONFIG_PACKAGE_kmod-crypto-deflate=y
		CONFIG_PACKAGE_kmod-crypto-echainiv=y
		CONFIG_PACKAGE_kmod-crypto-kpp=y
		CONFIG_PACKAGE_kmod-crypto-lib-chacha20=y
		CONFIG_PACKAGE_kmod-crypto-lib-chacha20poly1305=y
		CONFIG_PACKAGE_kmod-crypto-lib-curve25519=y
		CONFIG_PACKAGE_kmod-crypto-lib-poly1305=y
		# CONFIG_PACKAGE_kmod-ip-vti is not set
		# CONFIG_PACKAGE_kmod-ip6-vti is not set
		CONFIG_PACKAGE_kmod-ipsec=y
		CONFIG_PACKAGE_kmod-ipsec4=y
		CONFIG_PACKAGE_kmod-ipsec6=y
		CONFIG_PACKAGE_kmod-ipt-ipsec=y
		CONFIG_PACKAGE_kmod-iptunnel6=y
		CONFIG_PACKAGE_kmod-udptunnel4=y
		CONFIG_PACKAGE_kmod-udptunnel6=y
		CONFIG_PACKAGE_kmod-wireguard=y
		# CONFIG_PACKAGE_kmod-xfrm-interface is not set
		CONFIG_PACKAGE_libgmp=y
		CONFIG_PACKAGE_libminiupnpc=y
		CONFIG_PACKAGE_libnatpmp=y
		CONFIG_PACKAGE_luci-proto-wireguard=y
		CONFIG_PACKAGE_nlbwmon=y
		CONFIG_PACKAGE_strongswan=y
		CONFIG_PACKAGE_strongswan-charon=y
		# CONFIG_PACKAGE_strongswan-charon-cmd is not set
		# CONFIG_PACKAGE_strongswan-default is not set
		# CONFIG_PACKAGE_strongswan-gencerts is not set
		CONFIG_PACKAGE_strongswan-ipsec=y
		# CONFIG_PACKAGE_strongswan-isakmp is not set
		# CONFIG_PACKAGE_strongswan-libnttfft is not set
		# CONFIG_PACKAGE_strongswan-libtls is not set
		CONFIG_PACKAGE_strongswan-minimal=y
		# CONFIG_PACKAGE_strongswan-mod-addrblock is not set
		CONFIG_PACKAGE_strongswan-mod-aes=y
		# CONFIG_PACKAGE_strongswan-mod-af-alg is not set
		# CONFIG_PACKAGE_strongswan-mod-agent is not set
		# CONFIG_PACKAGE_strongswan-mod-attr is not set
		# CONFIG_PACKAGE_strongswan-mod-attr-sql is not set
		# CONFIG_PACKAGE_strongswan-mod-bliss is not set
		# CONFIG_PACKAGE_strongswan-mod-blowfish is not set
		# CONFIG_PACKAGE_strongswan-mod-ccm is not set
		# CONFIG_PACKAGE_strongswan-mod-chapoly is not set
		# CONFIG_PACKAGE_strongswan-mod-cmac is not set
		# CONFIG_PACKAGE_strongswan-mod-connmark is not set
		# CONFIG_PACKAGE_strongswan-mod-constraints is not set
		# CONFIG_PACKAGE_strongswan-mod-coupling is not set
		# CONFIG_PACKAGE_strongswan-mod-ctr is not set
		# CONFIG_PACKAGE_strongswan-mod-curl is not set
		# CONFIG_PACKAGE_strongswan-mod-curve25519 is not set
		# CONFIG_PACKAGE_strongswan-mod-des is not set
		# CONFIG_PACKAGE_strongswan-mod-dhcp is not set
		# CONFIG_PACKAGE_strongswan-mod-dnskey is not set
		# CONFIG_PACKAGE_strongswan-mod-duplicheck is not set
		# CONFIG_PACKAGE_strongswan-mod-eap-identity is not set
		# CONFIG_PACKAGE_strongswan-mod-eap-md5 is not set
		# CONFIG_PACKAGE_strongswan-mod-eap-mschapv2 is not set
		# CONFIG_PACKAGE_strongswan-mod-eap-radius is not set
		# CONFIG_PACKAGE_strongswan-mod-eap-tls is not set
		# CONFIG_PACKAGE_strongswan-mod-farp is not set
		# CONFIG_PACKAGE_strongswan-mod-fips-prf is not set
		# CONFIG_PACKAGE_strongswan-mod-forecast is not set
		# CONFIG_PACKAGE_strongswan-mod-gcm is not set
		# CONFIG_PACKAGE_strongswan-mod-gcrypt is not set
		CONFIG_PACKAGE_strongswan-mod-gmp=y
		# CONFIG_PACKAGE_strongswan-mod-gmpdh is not set
		# CONFIG_PACKAGE_strongswan-mod-ha is not set
		CONFIG_PACKAGE_strongswan-mod-hmac=y
		CONFIG_PACKAGE_strongswan-mod-kernel-libipsec=y
		CONFIG_PACKAGE_strongswan-mod-kernel-netlink=y
		# CONFIG_PACKAGE_strongswan-mod-ldap is not set
		# CONFIG_PACKAGE_strongswan-mod-led is not set
		# CONFIG_PACKAGE_strongswan-mod-load-tester is not set
		# CONFIG_PACKAGE_strongswan-mod-md4 is not set
		# CONFIG_PACKAGE_strongswan-mod-md5 is not set
		# CONFIG_PACKAGE_strongswan-mod-mgf1 is not set
		# CONFIG_PACKAGE_strongswan-mod-mysql is not set
		# CONFIG_PACKAGE_strongswan-mod-newhope is not set
		CONFIG_PACKAGE_strongswan-mod-nonce=y
		# CONFIG_PACKAGE_strongswan-mod-ntru is not set
		# CONFIG_PACKAGE_strongswan-mod-openssl is not set
		# CONFIG_PACKAGE_strongswan-mod-pem is not set
		# CONFIG_PACKAGE_strongswan-mod-pgp is not set
		# CONFIG_PACKAGE_strongswan-mod-pkcs1 is not set
		# CONFIG_PACKAGE_strongswan-mod-pkcs11 is not set
		# CONFIG_PACKAGE_strongswan-mod-pkcs12 is not set
		# CONFIG_PACKAGE_strongswan-mod-pkcs7 is not set
		# CONFIG_PACKAGE_strongswan-mod-pkcs8 is not set
		CONFIG_PACKAGE_strongswan-mod-pubkey=y
		CONFIG_PACKAGE_strongswan-mod-random=y
		# CONFIG_PACKAGE_strongswan-mod-rc2 is not set
		# CONFIG_PACKAGE_strongswan-mod-resolve is not set
		# CONFIG_PACKAGE_strongswan-mod-revocation is not set
		CONFIG_PACKAGE_strongswan-mod-sha1=y
		# CONFIG_PACKAGE_strongswan-mod-sha2 is not set
		# CONFIG_PACKAGE_strongswan-mod-sha3 is not set
		# CONFIG_PACKAGE_strongswan-mod-smp is not set
		CONFIG_PACKAGE_strongswan-mod-socket-default=y
		# CONFIG_PACKAGE_strongswan-mod-socket-dynamic is not set
		# CONFIG_PACKAGE_strongswan-mod-sql is not set
		# CONFIG_PACKAGE_strongswan-mod-sqlite is not set
		# CONFIG_PACKAGE_strongswan-mod-sshkey is not set
		CONFIG_PACKAGE_strongswan-mod-stroke=y
		# CONFIG_PACKAGE_strongswan-mod-test-vectors is not set
		# CONFIG_PACKAGE_strongswan-mod-uci is not set
		# CONFIG_PACKAGE_strongswan-mod-unity is not set
		CONFIG_PACKAGE_strongswan-mod-updown=y
		# CONFIG_PACKAGE_strongswan-mod-vici is not set
		# CONFIG_PACKAGE_strongswan-mod-whitelist is not set
		CONFIG_PACKAGE_strongswan-mod-x509=y
		# CONFIG_PACKAGE_strongswan-mod-xauth-eap is not set
		CONFIG_PACKAGE_strongswan-mod-xauth-generic=y
		CONFIG_PACKAGE_strongswan-mod-xcbc=y
		# CONFIG_PACKAGE_strongswan-pki is not set
		# CONFIG_PACKAGE_strongswan-scepclient is not set
		# CONFIG_PACKAGE_strongswan-swanctl is not set
		CONFIG_PACKAGE_vsftpd-alt=y
		CONFIG_PACKAGE_wireguard-tools=y
		# CONFIG_PACKAGE_xfrm is not set
		CONFIG_PACKAGE_zerotier=y
		CONFIG_STRONGSWAN_ROUTING_TABLE="220"
		CONFIG_STRONGSWAN_ROUTING_TABLE_PRIO="220"
		CONFIG_VSFTPD_USE_UCI_SCRIPTS=y
		# CONFIG_ZEROTIER_ENABLE_DEBUG is not set
		# CONFIG_ZEROTIER_ENABLE_SELFTEST is not set
          EOF

          #
          # ===============================================================
          # 

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
          df -h

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h ./ --max-depth=1
          du -h /mnt/openwrt/ --max-depth=1 || true

      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
